# Generated by Django 5.0.4 on 2024-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(default=1, verbose_name='What is on your mind?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Put a title'),
        ),
    ]
