# Generated by Django 5.0.4 on 2024-05-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_date',
            new_name='comment_date',
        ),
    ]
